### ISSUE TITLE
Is this real time?

### ISSUE THREAD

**Issue by yml-blog** [LNshuti/etf-tracker#1]

**Comment by LNshuti** [comment]
It's updated on execution to fetch data up to the current trading day. This is how I define the  date range: 

`
with ThreadPoolExecutor() as executor:

future_to_company = {
  executor.submit(fetch_historical_data, COMPANY_TICKERS[company], '2000-01-01', datetime.now().strftime('%Y-%m-%d')):(company, indicator)
for company in company_names
for indicator in indicator_types
}
`

All the code is open source and available here: https://huggingface.co/spaces/LeonceNsh/etf-tracker/blob/main/app.py
